AWSTemplateFormatVersion: '2010-09-09'
Description: 2 Tier Flask App via EC2 UserData with Elastic IP

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: DevOpsKey
    Description: EC2 KeyPair for SSH access (must already exist)

Resources:
  WebAppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH & HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0  

  WebAppEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref WebAppSG
      ImageId: ami-020cba7c55df1f615  # Ubuntu 22.04 in us-east-1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /var/log/user-data.log 2>&1
          set -xe
          apt update -y
          apt install -y python3-pip git
          git clone https://github.com/tylerleee5/2tier-simple.git /home/ubuntu/app
          cd /home/ubuntu/app
          pip3 install --break-system-packages --ignore-installed --no-cache-dir -r requirements.txt
          sudo chown -R ubuntu:ubuntu /home/ubuntu/app
          nohup python3 app.py > /home/ubuntu/app/app.log 2>&1 &

  # Add Elastic IP
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebAppEC2
      Domain: vpc

Outputs:
  PublicIP:
    Description: Static Public IPv4 of EC2 (Elastic IP)
    Value: !Ref ElasticIP
    Export:
      Name: EC2PublicIP
  
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref WebAppEC2
    Export:
      Name: EC2InstanceId