name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Flask App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get EC2 Public IP
        id: get-ip
        run: |
          # Option 1: If you know the instance ID
          EC2_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          
          # Option 2: If you want to find by tag (alternative)
          # EC2_IP=$(aws ec2 describe-instances \
          #   --filters "Name=tag:Name,Values=WebAppEC2" "Name=instance-state-name,Values=running" \
          #   --query 'Reservations[0].Instances[0].PublicIpAddress' \
          #   --output text)
          
          echo "EC2_IP=$EC2_IP" >> $GITHUB_OUTPUT
          echo "Found EC2 IP: $EC2_IP"

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ steps.get-ip.outputs.EC2_IP }} << 'EOF'
            cd /home/ubuntu/app
            git pull origin main
            pip3 install --break-system-packages --ignore-installed --no-cache-dir -r requirements.txt
            pkill -f app.py || true
            sleep 2
            nohup python3 app.py > /home/ubuntu/app/app.log 2>&1 &
          EOF

